### ISSUE TITLE
기능구현 - 고객센터/메인(cs/index)

### ISSUE THREAD

**Issue by hwangwonjin** [lazca2080/Kmarket#48]
http://localhost:8080/Kmarket/cs/index.do

**Comment by Yiwonjeong** [comment]
- 2022/12/13
- cs::index
- [ ] index.jsp
- [ ] indexController 최신글 5개 리스트 가져오기
- [ ] csService
- [ ] csDAO
- [ ] csVO
- [ ] csSql
