### ISSUE TITLE
기능구현 - 회원/일반가입(member/register)

### ISSUE THREAD

**Issue by lazca2080** [lazca2080/Kmarket#54]
http://localhost:8080/Kmarket/member/register.do

**Comment by Yiwonjeong** [comment]
2022/12/12

- 일반 회원가입 
- [ ] 사용자 기본 정보 입력
- [ ] 아이디 중복체크, 형식 검사
- [ ] 비밀번호 일치 및 형식 검사
- [ ] 이름 입력 및 형식 검사
- [ ] 성별 선택
- [ ] 이메일 입력 및 형식 검사
- [ ] 휴대폰 입력 및 형식 검사
- [ ] 주소 입력 

- 회원가입 버튼 클릭 시 테이블 INSERT
